### ISSUE TITLE
How to dimension C9, C11 and R10

### ISSUE THREAD

**Issue by simon88** [azerimaker/Penguino-STM32WL-LoRa-E5#9]
Hi,

Nice works, I'm interresting to use it but I have a question, how to dimension  C9, C11 and R10 for RF part?

**Comment by azerimaker** [comment]
Hi, @simon88. 

Thank you for interest. C9, C11 and R10 forms a circuit which is typically called a Pi matching network, in this case to match the impedance of the RF module (*typically 50 Ohms) to the antenna (can vary significantly depending on the quality). 
If you have a well matched antenna then you can simply short R10 with 0 Ohm resistor and leave others unpopulated. 

Otherwise, you need a Vector Network Analyzer (VNA) to properly measure the impedance of the antenna while the device is installed on its final enclosure and use online calculator like [this one](https://www.allaboutcircuits.com/tools/pi-match-impedance-matching-calculator/) to calculate the exact inductor and capacitor values. 

![QGgWZ](https://user-images.githubusercontent.com/2662257/145988088-b5548df3-0d77-4402-ae1d-037c1671a8e1.jpg)

**Comment by simon88** [comment]
@azerimaker thanks a lot for this very useful answer :)
